const InspirationalSayings = [
    'Don\’t tell me the sky’s the limit when I know there are footprints on the moon',
    'We are all made of stardust',
    'We are the makers of our own destiny',
    'The future is in our hands',
    'A bend is the road is not the end unless you choose not to take the turn',
    'Happiness can be found even in the darkest of times, if one only remembers to turn on the light',
    'Your day goes the direction the corners of your mouth turn',
    'Don\'t make a permanent decision because of your temporary emotion',
    'Great things never come from comfort zones',
    'You don\’t have to attend every argument you are invited to',
    'Do what is right, not what is easy',
    'You are never too old to set another goal or to dream another dream',
    'Don\’t try to rush things that need time to grow',
    'Be good to people - You will be remembered more for your kindness than any level of success you could possibly attain',
    'I am - Two of the most powerful words for what you put after them shapes your reality',
    'What defines us is how well we rise after falling',
    'Your beliefs don\’t make you a better person – Your behavior does',
    'Stop hiding your scars and your wounds – They\’re your trophies that you went through that and still survived',
    'Your hardest times will often lead to the greatest moments of your life',
    'There are seven days in a week, amd someday is not one of them',
    'It\’s a beautiful day to start',
    'Don\’t let your struggle become your identity',
    'The light shines in the darkness and the darkness can never extinguish it',
    'Kind words cost nothing',
    'Be a pineapple - stand tall, wear a crown and be sweet on the inside',
    'A setback is a set up for a comeback',
    'Hope is being able to see the light despite all the darkness',
    'Most of life\’s great changes are preceded by chaos',
    'Worry is worshipping the problem',
    'In a world where you can be anything, be kind',
    'There are no elevators to success. You have to take the stairs',
    'Every accomplishment starts with the decision to try',
    'Stop trying to make everybody happy. You aren\’t chocolate',
    'Your dream doesn\’t have to have an expiration date. Take a deep breath and try again',
    'Attitudes are contagious - make yours worth catching',
    'Trust that an ending is always followed by a new beginning',
    'The right word at the right time is like precious gold set in silver',
    'When you hold on to your history, you do it at the expense of your destiny',
    'Some people come into your life as blessings. Some come into your life as lessons',
    'Stop being afraid of what could go wrong and think of what could go right',
    'Every flower must grow through dirt.',
    'If it does not challenge you, it does not change you',
    'You have been assigned this mountain to show others that it can be moved',
    'Perhaps the butterfly is proof that you can go through a great deal of darkness yet become something beautiful',
    'We\’re all so desperate to be understood but we forget to be understanding',
    'Take the risk or lose the chance',
    'If a door closes, quit banging on it. Perhaps it closed because you are worth so much more than what is on the other side',
    'When the world says "give up," hope whispers "try it one more time"',
    'The future belongs to those who believe in the beauty of their dreams',
    'Everything will be okay in the end. If it is not okay, it is not the end',
    'Fairy tales are more than true - not because they tell us that dragons exist, but because they tell us that dragons can be beaten',
    'The same boiling water that softens the potato hardens the egg - it is not the circumstances but what you are made of',
    'People who wonder if the glass is half full or half empty miss the point - the glass is refillable',
    'One day or day one - you can decide',
    'Hard work beats talent when talent doesn\’t work hard',
    'Sometimes when you\’re in a dark place you think you\’ve been buried, but you\’ve really been planted',
    'Don\’t limit your challenges, challenge your limits',
    'Always keep your face towards the sunshine and the shadows will fall behind you',
    'Doubt kills more dreams than failure ever will',
    'You never lose. Either you win or you learn',
    'Don\’t compare yourself to others. Be like the sun and moon and shine when it’s your time',
    'You can\’t go back and change the beginning, but you can start where you are and change the ending',
    'The question isn\’t who is going to let me, it\’s who is going to stop me',
    'When plan A doesn’t work, don\’t worry, you still have 25 more letters to go through',
    'A diamond is merely a lump of coal that did well under pressure',
    'You can\'t have a rainbow without a little rain',
    'If you want to fly, you have to give up everything that weighs you down.',
    'Nothing is impossible - the word itself says "I\'m possible!"',
    'Happiness often sneaks in through a door you didn\'t know you left open',
    'It\'s okay to be a glowstick - sometimes we have to break before we shine',
    'The key to success is to start before you are ready',
    'If opportunity doessn\'t knock, build a door',
    'Even if you are on the right track, you\'ll just get run over if you just stay there',
    'The best is yet to come',
    'Hard times are sometimes blessings in disguise',
    'Life will always give you a second chance - it\'s called tomorrow',
    'Be yourself. Everyone else is already taken',
    'People are like stained-glass windows. They sparkle and shine when the sun shines, but when darkness sets, their true beauty is shown only if there is light from within',
    'Don\'t be pushed by your problems - be led by your dreams',
    'Difficult roads often lead to beautiful destinations'
];

// random inspirational saying
function getInspiration() {
    const randomSaying = Math.floor(Math.random() * (InspirationalSayings.length));
    document.getElementById("DisplayInspiration").innerHTML = InspirationalSayings[randomSaying];
}